import pg from 'pg';
import { schemaSql } from './schema.js';
export class Database {
  private pool: pg.Pool;
  constructor() { this.pool = new pg.Pool({ connectionString: process.env.DATABASE_URL }); }
  async init() { await this.pool.query(schemaSql); }
  async persistFleet(ships: any[]) { for (const s of ships) await this.pool.query('INSERT INTO ships(id,name,status,latitude,longitude,speed,heading,fuel_remaining,destination,cargo) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,latitude=EXCLUDED.latitude,longitude=EXCLUDED.longitude,speed=EXCLUDED.speed,heading=EXCLUDED.heading,fuel_remaining=EXCLUDED.fuel_remaining,destination=EXCLUDED.destination,cargo=EXCLUDED.cargo,updated_at=now()',[s.id,s.name,s.status,s.latitude,s.longitude,s.speed,s.heading,s.fuel,JSON.stringify(s.destination),JSON.stringify(s.cargo)]); }
  async persistRoute(ship:any) { if(!ship.route?.length)return;await this.pool.query('INSERT INTO ship_routes(ship_id,geometry,route_status) VALUES($1,ST_GeomFromGeoJSON($2),$3)',[ship.id,JSON.stringify({type:'LineString',coordinates:ship.route.map((p:any)=>[p.lng,p.lat])}),ship.status]); }
  async persistDirective(shipId:string,d:any) { await this.pool.query('INSERT INTO directives(id,ship_id,type,payload,status,created_by,responded_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,responded_at=EXCLUDED.responded_at',[d.id,shipId,d.type,JSON.stringify(d.payload),d.status,'COMMAND',d.status==='PENDING'?null:new Date()]); }
  async event(type: string, shipId: string | null, payload: unknown) { await this.pool.query('INSERT INTO system_events(type,ship_id,payload) VALUES($1,$2,$3)', [type, shipId, payload]); }
  async persistZone(z: any) { const ring = z.polygon.map((p: any) => [p.lng, p.lat]); ring.push(ring[0]); await this.pool.query('INSERT INTO restricted_zones(id,name,geometry,created_by) VALUES($1,$2,ST_GeomFromGeoJSON($3),$4) ON CONFLICT(id) DO UPDATE SET name=$2,geometry=EXCLUDED.geometry,updated_at=now()', [z.id,z.name,JSON.stringify({type:'Polygon',coordinates:[ring]}),z.createdBy]); }
  async deleteZone(id: string) { await this.pool.query('DELETE FROM restricted_zones WHERE id=$1',[id]); }
  async persistAlert(a: any) { await this.pool.query('INSERT INTO alerts(id,ship_id,type,severity,title,message,metadata,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,acknowledged_at=CASE WHEN EXCLUDED.status=\'ACKNOWLEDGED\' THEN now() ELSE alerts.acknowledged_at END,resolved_at=CASE WHEN EXCLUDED.status=\'RESOLVED\' THEN now() ELSE alerts.resolved_at END',[a.id,a.shipId,a.type,a.severity,a.type.replaceAll('_',' '),a.message,JSON.stringify(a.metadata),a.status]); }
  async distress(shipId:string,message:string,analysis:any) { await this.pool.query('INSERT INTO distress_events(id,ship_id,message,severity,issue,injury_count,damage_estimate,ai_analysis) VALUES($1,$2,$3,$4,$5,$6,$7,$8)', [`distress_${crypto.randomUUID()}`,shipId,message,analysis.severity,analysis.issue,analysis.injuryCount,null,JSON.stringify(analysis)]); }
  async weather(data:any) { await this.pool.query('INSERT INTO weather_snapshots(data) VALUES($1)',[JSON.stringify(data)]); }
  async snapshot(ships: any[]) { const q = 'INSERT INTO ship_snapshots(ship_id,timestamp,latitude,longitude,speed,heading,fuel_remaining,status) VALUES '+ships.map((_,i)=>`($${i*7+1},now(),$${i*7+2},$${i*7+3},$${i*7+4},$${i*7+5},$${i*7+6},$${i*7+7})`).join(','); await this.pool.query(q, ships.flatMap(s=>[s.id,s.latitude,s.longitude,s.speed,s.heading,s.fuel,s.status])); }
  async history() { const r=await this.pool.query('SELECT DISTINCT ON (ship_id, bucket) ship_id,timestamp,latitude,longitude,speed,heading,fuel_remaining,status FROM (SELECT *, date_bin(\'30 seconds\', timestamp, TIMESTAMPTZ \'2000-01-01 00:00:00+00\') bucket FROM ship_snapshots WHERE timestamp > now() - interval \'1 hour\') x ORDER BY ship_id,bucket,timestamp DESC'); return r.rows; }
}
